# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0002_auto_20170828_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='desc',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
